export const semesters = ["Spring 2024",  "Fall 2023",  "Spring 2023",  "Fall 2022",  "Spring 2022",  "Fall 2021",  "Spring 2021",  "Fall 2020",  "Spring 2020",  "Fall 2019",  "Spring 2019",  "Fall 2018",  "Spring 2018",  "Fall 2017",  "Spring 2017",  "Fall 2016",  "Spring 2016"]
export const subjects = ["AAE", "AAS", "ABE", "AD", "AFT", "AGEC", "AGR", "AGRY", "AMST", "ANSC", "ANTH", "ARAB", "ASAM", "ASEC", "ASL", "ASM", "ASTR", "AT", "BAND", "BCHM", "BIOL", "BME", "BMS", "BTNY", "CAND", "CDIS", "CE", "CEM", "CGT", "CHE", "CHM", "CHNS", "CLCS", "CLPH", "CM", "CMPL", "CNIT", "COM", "CPB", "CS", "CSR", "DANC", "EAPS", "ECE", "ECET", "ECON", "EDCI", "EDPS", "EDST", "EEE", "ENE", "ENGL", "ENGR", "ENGT", "ENTM", "ENTR", "EPCS", "FNR", "FR", "FS", "FVS", "GEP", "GER", "GRAD", "GREK", "GS", "GSLA", "HDFS", "HEBR", "HIST", "HK", "HONR", "HORT", "HSCI", "HSOP", "HTM", "IDE", "IDIS", "IE", "IET", "ILS", "IPPH", "IT", "ITAL", "JPNS", "JWST", "KOR", "LA", "LALS", "LATN", "LC", "LING", "MA", "MCMP", "ME", "MET", "MFET", "MGMT", "MSE", "MSL", "MUS", "NRES", "NS", "NUCL", "NUPH", "NUR", "NUTR", "OBHR", "OLS", "PES", "PHIL", "PHPR", "PHRM", "PHYS", "POL", "PSY", "PTGS", "PUBH", "REG", "REL", "RUSS", "SA", "SCI", "SCLA", "SFS", "SLHS", "SOC", "SPAN", "STAT", "SYS", "TDM", "TECH", "THTR", "TLI",  "VCS",  "VIP",  "VM", "WGSS"]

export const subjectOptions = [
  {value: "AAE", label: "AAE: Aero & Astro Engineering"},
  {value: "AAS", label: "AAS: African American Studies"},
  {value: "ABE", label: "ABE: Agri & Biol Engineering"},
  {value: "AD", label: "AD: Art & Design"},
  {value: "AFT", label: "AFT: Aerospace Studies"},
  {value: "AGEC", label: "AGEC: Agricultural Economics"},
  {value: "AGR", label: "AGR: Agriculture"},
  {value: "AGRY", label: "AGRY: Agronomy"},
  {value: "AMST", label: "AMST: American Studies"},
  {value: "ANSC", label: "ANSC: Animal Sciences"},
  {value: "ANTH", label: "ANTH: Anthropology"},
  {value: "ARAB", label: "ARAB: Arabic"},
  {value: "ASAM", label: "ASAM: Asian American Studies"},
  {value: "ASEC", label: "ASEC: Agric Sciences Educ &Comm"},
  {value: "ASL", label: "ASL: American Sign Language"},
  {value: "ASM", label: "ASM: Agricultural Systems Mgmt"},
  {value: "ASTR", label: "ASTR: Astronomy"},
  {value: "AT", label: "AT: Aviation Technology"},
  {value: "BAND", label: "BAND: Bands"},
  {value: "BCHM", label: "BCHM: Biochemistry"},
  {value: "BIOL", label: "BIOL: Biological Sciences"},
  {value: "BME", label: "BME: Biomedical Engineering"},
  {value: "BMS", label: "BMS: Basic Medical Sciences"},
  {value: "BTNY", label: "BTNY: Botany & Plant Pathology"},
  {value: "CAND", label: "CAND: Candidate"},
  {value: "CDIS", label: "CDIS: Critical Disability Std"},
  {value: "CE", label: "CE: Civil Engineering"},
  {value: "CEM", label: "CEM: Construction Engr & Mgmt"},
  {value: "CGT", label: "CGT: Computer Graphics Tech"},
  {value: "CHE", label: "CHE: Chemical Engineering"},
  {value: "CHM", label: "CHM: Chemistry"},
  {value: "CHNS", label: "CHNS: Chinese"},
  {value: "CLCS", label: "CLCS: Classics"},
  {value: "CLPH", label: "CLPH: Clinical Pharmacy"},
  {value: "CM", label: "CM: Construction Management"},
  {value: "CMPL", label: "CMPL: Comparative Literature"},
  {value: "CNIT", label: "CNIT: Computer & Info Tech"},
  {value: "COM", label: "COM: Communication"},
  {value: "CPB", label: "CPB: Comparative Pathobiology"},
  {value: "CS", label: "CS: Computer Sciences"},
  {value: "CSR", label: "CSR: Consumer Science"},
  {value: "DANC", label: "DANC: Dance"},
  {value: "EAPS", label: "EAPS: Earth Atmos Planetary Sci"},
  {value: "ECE", label: "ECE: Electrical & Computer Engr"},
  {value: "ECET", label: "ECET: Electrical&Comp Engr Tech"},
  {value: "ECON", label: "ECON: Economics"},
  {value: "EDCI", label: "EDCI: Educ-Curric & Instruction"},
  {value: "EDPS", label: "EDPS: Educ-Ed'l and Psy Studies"},
  {value: "EDST", label: "EDST: Ed Leadrship&Cultrl Fnd"},
  {value: "EEE", label: "EEE: Environ & Ecological Engr"},
  {value: "ENE", label: "ENE: Engineering Education"},
  {value: "ENGL", label: "ENGL: English"},
  {value: "ENGR", label: "ENGR: Engineering"},
  {value: "ENGT", label: "ENGT: Engineering Technology"},
  {value: "ENTM", label: "ENTM: Entomology"},
  {value: "ENTR", label: "ENTR: Entrepreneurship"},
  {value: "EPCS", label: "EPCS: Engr Proj Cmity Service"},
  {value: "FNR", label: "FNR: Forestry&Natural Resources"},
  {value: "FR", label: "FR: French"},
  {value: "FS", label: "FS: Food Science"},
  {value: "FVS", label: "FVS: Film And Video Studies"},
  {value: "GEP", label: "GEP: Global Engineering Program"},
  {value: "GER", label: "GER: German"},
  {value: "GRAD", label: "GRAD: Graduate Studies"},
  {value: "GREK", label: "GREK: Greek"},
  {value: "GS", label: "GS: General Studies"},
  {value: "GSLA", label: "GSLA: Global Studies Lib Arts"},
  {value: "HDFS", label: "HDFS: Human Dev & Family Sci"},
  {value: "HEBR", label: "HEBR: Hebrew"},
  {value: "HIST", label: "HIST: History"},
  {value: "HK", label: "HK: Health And Kinesiology"},
  {value: "HONR", label: "HONR: Honors"},
  {value: "HORT", label: "HORT: Horticulture"},
  {value: "HSCI", label: "HSCI: Health Sciences"},
  {value: "HSOP", label: "HSOP: Hlth Srvcs Outcomes & Polic"},
  {value: "HTM", label: "HTM: Hospitality & Tourism Mgmt"},
  {value: "IDE", label: "IDE: Interdisciplinary Engr"},
  {value: "IDIS", label: "IDIS: Interdisciplinary Studies"},
  {value: "IE", label: "IE: Industrial Engineering"},
  {value: "IET", label: "IET: Industrial Engr Technology"},
  {value: "ILS", label: "ILS: Information & Library Sci"},
  {value: "IPPH", label: "IPPH: Industrial & Phys Pharm"},
  {value: "IT", label: "IT: Industrial Technology"},
  {value: "ITAL", label: "ITAL: Italian"},
  {value: "JPNS", label: "JPNS: Japanese"},
  {value: "JWST", label: "JWST: Jewish Studies"},
  {value: "KOR", label: "KOR: Korean"},
  {value: "LA", label: "LA: Landscape Architecture"},
  {value: "LALS", label: "LALS: Latina Am & Latino Studies"},
  {value: "LATN", label: "LATN: Latin"},
  {value: "LC", label: "LC: Languages and Cultures"},
  {value: "LING", label: "LING: Linguistics"},
  {value: "MA", label: "MA: Mathematics"},
  {value: "MCMP", label: "MCMP: Med Chem &Molecular Pharm"},
  {value: "ME", label: "ME: Mechanical Engineering"},
  {value: "MET", label: "MET: Mechanical Engr Tech"},
  {value: "MFET", label: "MFET: Manufacturing Engr Tech"},
  {value: "MGMT", label: "MGMT: Management"},
  {value: "MSE", label: "MSE: Materials Engineering"},
  {value: "MSL", label: "MSL: Military Science & Ldrshp"},
  {value: "MUS", label: "MUS: Music History & Theory"},
  {value: "NRES", label: "NRES: Natural Res & Environ Sci"},
  {value: "NS", label: "NS: Naval Science"},
  {value: "NUCL", label: "NUCL: Nuclear Engineering"},
  {value: "NUPH", label: "NUPH: Nuclear Pharmacy"},
  {value: "NUR", label: "NUR: Nursing"},
  {value: "NUTR", label: "NUTR: Nutrition Science"},
  {value: "OBHR", label: "OBHR: Orgnztnl Bhvr & Hum Resrce"},
  {value: "OLS", label: "OLS: Organiz Ldrshp & Supervision"},
  {value: "PES", label: "PES: Physical Education Skills"},
  {value: "PHIL", label: "PHIL: Philosophy"},
  {value: "PHPR", label: "PHPR: Pharmacy Practice"},
  {value: "PHRM", label: "PHRM: Pharmacy"},
  {value: "PHYS", label: "PHYS: Physics"},
  {value: "POL", label: "POL: Political Science"},
  {value: "PSY", label: "PSY: Psychological Sciences"},
  {value: "PTGS", label: "PTGS: Portuguese"},
  {value: "PUBH", label: "PUBH: Public Health"},
  {value: "REG", label: "REG: Reg File Maintenance"},
  {value: "REL", label: "REL: Religious Studies"},
  {value: "RUSS", label: "RUSS: Russian"},
  {value: "SA", label: "SA: Study Abroad"},
  {value: "SCI", label: "SCI: General Science"},
  {value: "SCLA", label: "SCLA: Studies Coll Liberal Arts"},
  {value: "SFS", label: "SFS: Sustainable Food & Farm Sys"},
  {value: "SLHS", label: "SLHS: Speech Lang & Hear Science"},
  {value: "SOC", label: "SOC: Sociology"},
  {value: "SPAN", label: "SPAN: Spanish"},
  {value: "STAT", label: "STAT: Statistics"},
  {value: "SYS", label: "SYS: Purdue Sys Collaboratory"},
  {value: "TDM", label: "TDM: The Data Mine"},
  {value: "TECH", label: "TECH: Technology"},
  {value: "THTR", label: "THTR: Theatre"},
  {value: "TLI", label: "TLI: Technology Ldrshp Innovatn"},
  {value: "VCS", label: "VCS: Veterinary Clinical Sci"},
  {value: "VIP", label: "VIP: Vertically Integrated Proj"},
  {value: "VM", label: "VM: Veterinary Medicine"},
  {value: "WGSS", label: "WGSS: Women Gend & Sexuality Std"}
]